import chroma from "chroma-js";
import sizes from "./sizes";

export default {
  ColorBox: {
    height: (props) => (props.showingFullPalette ? "25%" : "50%"),
    minHeight: (props) => (props.showingFullPalette ? "150px" : "300px"),
    width: "20%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.5px",
    "&:hover button": {
      opacity: "1",
      transition: "0.3s ease",
    },
    [sizes.down("lg")]: {
      width: "25%",
      // height: (props) => (props.showingFullPalette ? "20%" : "50%"),
    },
    [sizes.down("md")]: {
      width: "50%",
      // height: (props) => (props.showingFullPalette ? "10%" : "50%"),
    },
    [sizes.down("xs")]: {
      width: "100%",
      // height: (props) => (props.showingFullPalette ? "5%" : "50%"),
    },
  },
  copyText: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.4 ? "black" : "white",
  },
  colorName: {
    color: (props) =>
      chroma(props.background).luminance() <= 0.4 ? "white" : "black",
  },
  seeMore: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.4 ? "rgba(0,0,0,.7)" : "white",
    position: "absolute",
    right: "0",
    bottom: "0",
    padding: "5px",
    textTransform: "uppercase",
    letterSpacing: "1",
    fontSize: "12",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    textAlign: "center",
  },
  copyButton: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.4 ? "black" : "white",
    width: "100px",
    height: "30px",
    position: "absolute",
    top: "50%",
    left: "50%",
    marginLeft: "-50px",
    marginTop: "-15px",
    cursor: "pointer",
    textAlign: "center",
    outline: "none",
    fontSize: "1rem",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    textTransform: "uppercase",
    lineHeight: "30px",
    border: "none",
    textDecoration: "none",
    transition: "0.3s ease",
    zIndex: "5px",
    opacity: "0",
  },
  boxContent: {
    position: "absolute",
    width: "100%",
    left: "0",
    bottom: "0",
    padding: "10px",
    color: "black",
    letterSpacing: "1px",
    textTransform: "uppercase",
    fontSize: "12px",
  },
  copyOverlay: {
    opacity: "0",
    zIndex: "0",
    width: "100%",
    height: "100%",
    transform: "scale(0.1)",
    transition: "transform 0.6s ease-in-out",
  },
  showOverlay: {
    opacity: "1",
    transform: "scale(50)",
    zIndex: "10",
    position: "absolute",
  },
  copyMessage: {
    position: "fixed",
    top: "0",
    right: "0",
    bottom: "0",
    left: "0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "4rem",
    opacity: "0",
    transform: "scale(0.1)",
    color: "white",
    "& h2": {
      fontWeight: "400",
      width: "100%",
      textShadow: "1px 2px black",
      backgroundColor: "rgba(255, 255, 255, 0.3)",
      textAlign: "center",
      textTransform: "uppercase",
      marginBottom: "0",
      padding: "1rem",
    },
    "& p": {
      fontSize: "2rem",
      fontWeight: "200",
    },
  },
  showMessage: {
    transitionDelay: "0.3s",
    transition: "all 0.4s ease-in-out",
    opacity: "1",
    transform: "scale(1)",
    zIndex: "20",
  },
};
