export default {
  root: {
    backgroundColor: "white",
    borderRadius: 5,
    border: "1px solid black",
    padding: ".5rem",
    position: "relative",
    overflow: "hidden",
    cursor: "pointer",
    "&:hover svg": {
      opacity: 1,
    },
  },
  colors: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gridTemplateRows: "repeat(4, 1fr)",
    height: "150px",
    width: "100%",
    borderRadius: "7px",
    overflow: "hidden",
  },
  title: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "black",
    paddingTop: ".5rem",
    fontSize: "1rem",
    position: "relative",
    margin: "10px 0",
  },
  emoji: {
    marginLeft: ".5rem",
    fontSize: "1.5rme",
  },
  miniColor: {
    height: "100%",
    width: "100%",
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
  },
  delete: {},
  deleteIcon: {
    color: "white",
    backgroundColor: "#eb3d30",
    width: "20px",
    height: "20px",
    position: "absolute",
    right: 0,
    top: 0,
    padding: 5,
    zIndex: 10,
    opacity: 0,
    borderBottomLeftRadius: 5,
    transition: ".3s ease-in-out",
  },
};
